BeCoreApp.Web/Models/BlogViewModels/CatalogViewModel.cs
using BeCoreApp.Application.ViewModels.Blog;
using BeCoreApp.Application.ViewModels.Common;
using BeCoreApp.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Models.BlogViewModels
{
    public class CatalogViewModel
    {
        public CatalogViewModel()
        {
            Blogs = new List<BlogViewModel>();
            Tags = new List<TagViewModel>();
            SideBarBlogCategorys = new List<BlogCategoryViewModel>();
        }
        public PagedResult<BlogViewModel> Data { get; set; }
        public List<BlogViewModel> Blogs { set; get; }
        public TagViewModel Tag { get; set; }
        public List<TagViewModel> Tags { get; set; }
        public BlogCategoryViewModel BlogCategory { get; set; }
        public List<BlogCategoryViewModel> SideBarBlogCategorys { get; set; }
        public string SearchValue { get; set; }
        public string SortType { set; get; }

        public int? PageSize { set; get; }

        public List<SelectListItem> SortTypes { get; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "1",Text = "Thông Thường"},
            new SelectListItem(){Value = "2",Text = "Tin Mới Nhất"}
        };

        public List<SelectListItem> PageSizes { get; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "0",Text = "ALL"},
            new SelectListItem(){Value = "10",Text = "10"},
            new SelectListItem(){Value = "20",Text = "20"},
            new SelectListItem(){Value = "40",Text = "40"},
        };
    }
}

BeCoreApp.Web/Models/BlogViewModels/DetailViewModel.cs
using BeCoreApp.Application.ViewModels.Blog;
using BeCoreApp.Application.ViewModels.Common;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Models.BlogViewModels
{
    public class DetailViewModel
    {
        public DetailViewModel()
        {
            Blogs = new List<BlogViewModel>();
            Tags = new List<TagViewModel>();
            BlogTags = new List<TagViewModel>();
            SideBarBlogCategorys = new List<BlogCategoryViewModel>();
        }
        public List<TagViewModel> BlogTags { get; set; }
        public BlogViewModel Blog { get; set; }
        public List<BlogViewModel> Blogs { set; get; }
        public List<BlogViewModel> BlogRelates { set; get; }
        public List<TagViewModel> Tags { get; set; }
        public BlogCategoryViewModel BlogCategory { get; set; }
        public List<BlogCategoryViewModel> SideBarBlogCategorys { get; set; }
    }
}

BeCoreApp.Web/Models/ProductViewModels/CatalogViewModel.cs
using BeCoreApp.Application.ViewModels.Blog;
using BeCoreApp.Application.ViewModels.Common;
using BeCoreApp.Application.ViewModels.Product;
using BeCoreApp.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Models.ProductViewModels
{
    public class CatalogViewModel
    {
        public CatalogViewModel()
        {
            Products = new List<ProductViewModel>();
            Tags = new List<TagViewModel>();
        }
        public PagedResult<ProductViewModel> Data { get; set; }
        public List<ProductViewModel> Products { set; get; }
        public TagViewModel Tag { get; set; }
        public List<TagViewModel> Tags { get; set; }
        public BlogCategoryViewModel BlogCategory { get; set; }

        public string SortType { set; get; }

        public int? PageSize { set; get; }

        public List<SelectListItem> SortTypes { get; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "1",Text = "Thông Thường"},
            new SelectListItem(){Value = "2",Text = "Tin Mới Nhất"}
        };

        public List<SelectListItem> PageSizes { get; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "0",Text = "ALL"},
            new SelectListItem(){Value = "10",Text = "10"},
            new SelectListItem(){Value = "20",Text = "20"},
            new SelectListItem(){Value = "40",Text = "40"},
        };
    }
}

BeCoreApp.Web/Models/ProductViewModels/DetailViewModel.cs
using BeCoreApp.Application.ViewModels.Common;
using BeCoreApp.Application.ViewModels.Product;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Models.ProductViewModels
{
    public class DetailViewModel
    {
        public DetailViewModel()
        {
            ProductTags = new List<TagViewModel>();
            RelatedProducts = new List<ProductViewModel>();
            Tags = new List<TagViewModel>();
        }
        public ProductViewModel Product { get; set; }
        public List<TagViewModel> ProductTags { get; set; }

        public List<ProductViewModel> RelatedProducts { get; set; }

        public List<TagViewModel> Tags { set; get; }
    }
}

BeCoreApp.Web/Models/ProjectViewModels/CatalogViewModel.cs
using BeCoreApp.Application.ViewModels.Project;
using BeCoreApp.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Models.ProjectViewModels
{
    public class CatalogViewModel
    {
        public CatalogViewModel()
        {
            ProjectVMs = new List<ProjectViewModel>();
            ProjectCategoryVMs = new List<ProjectCategoryViewModel>();
        }
        public PagedResult<ProjectViewModel> Data { get; set; }
        public List<ProjectViewModel> ProjectVMs { set; get; }
        public ProjectCategoryViewModel ProjectCategoryVM { get; set; }
        public List<ProjectCategoryViewModel> ProjectCategoryVMs { set; get; }

        public string SortType { set; get; }
        public int? PageSize { set; get; }

        public List<SelectListItem> SortTypes { get; set; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "1",Text = "Thông Thường"},
            new SelectListItem(){Value = "2",Text = "Tin Mới Nhất"}
        };

        public List<SelectListItem> PageSizes { get; } = new List<SelectListItem>
        {
            new SelectListItem(){Value = "0",Text = "ALL"},
            new SelectListItem(){Value = "12",Text = "12"},
            new SelectListItem(){Value = "24",Text = "24"},
            new SelectListItem(){Value = "48",Text = "48"},
        };
    }
}

BeCoreApp.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using BeCoreApp.Application.Interfaces;
using BeCoreApp.Application.ViewModels.Product;
using BeCoreApp.Data.Enums;
using BeCoreApp.Utilities.Constants;
using BeCoreApp.Utilities.Helpers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using OfficeOpenXml.Table;

namespace BeCoreApp.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;
        private readonly IBlogCategoryService _blogCategoryService;
        private readonly IHostingEnvironment _hostingEnvironment;
        public ProductController(IProductService productService,
             IBlogCategoryService blogCategoryService,
            IHostingEnvironment hostingEnvironment)
        {
            _blogCategoryService = blogCategoryService;
            _productService = productService;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            var tags = _productService.GetListTagByType(CommonConstants.ProductTag);
            ViewBag.Tags = new SelectList(tags, "Id", "Name");

            var productTypes = _productService.GetAllProductType();
            ViewBag.ProductTypes = new SelectList(productTypes, "Id", "Name");
            return View();
        }

        [HttpGet]
        public IActionResult GetAllBlogCategory()
        {
            var model = _blogCategoryService.GetTreeAll();
            return new ObjectResult(model);
        }

        #region AJAX API

        [HttpGet]
        public IActionResult GetAllPaging(string keyword, int blogCategoryId, int page, int pageSize)
        {
            var model = _productService.GetAllPaging("", "", keyword, blogCategoryId, page, pageSize);
            return new OkObjectResult(model);
        }

        [HttpGet]
        public IActionResult GetById(int id)
        {
            var model = _productService.GetById(id);
            return new OkObjectResult(model);
        }

        [HttpPost]
        public IActionResult SaveEntity(ProductViewModel productVm)
        {
            if (!ModelState.IsValid)
                return new BadRequestObjectResult(ModelState.Values.SelectMany(v => v.Errors));
            else
            {
                if (productVm.Id == 0)
                    _productService.Add(productVm);
                else
                    _productService.Update(productVm);

                _productService.Save();
                return new OkObjectResult(productVm);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
                return new BadRequestObjectResult(ModelState);
            else
            {
                _productService.Delete(id);
                _productService.Save();

                return new OkObjectResult(id);
            }
        }

        [HttpPost]
        public IActionResult SaveQuantities(int productId, List<ProductQuantityViewModel> quantities)
        {
            _productService.AddQuantity(productId, quantities);
            _productService.Save();
            return new OkObjectResult(quantities);
        }

        [HttpGet]
        public IActionResult GetQuantities(int productId)
        {
            var quantities = _productService.GetQuantities(productId);
            return new OkObjectResult(quantities);
        }

        [HttpPost]
        public IActionResult SaveImages(int productId, string[] images)
        {
            _productService.AddImages(productId, images);
            _productService.Save();
            return new OkObjectResult(images);
        }

        [HttpGet]
        public IActionResult GetImages(int productId)
        {
            var images = _productService.GetImages(productId);
            return new OkObjectResult(images);
        }

        [HttpPost]
        public IActionResult SaveWholePrice(int productId, List<WholePriceViewModel> wholePrices)
        {
            _productService.AddWholePrice(productId, wholePrices);
            _productService.Save();
            return new OkObjectResult(wholePrices);
        }

        [HttpGet]
        public IActionResult GetWholePrices(int productId)
        {
            var wholePrices = _productService.GetWholePrices(productId);
            return new OkObjectResult(wholePrices);
        }

        [HttpPost]
        public IActionResult ImportExcel(IList<IFormFile> files, int categoryId)
        {
            if (files != null && files.Count > 0)
            {
                var file = files[0];
                var filename = ContentDispositionHeaderValue
                                   .Parse(file.ContentDisposition)
                                   .FileName
                                   .Trim('"');

                string folder = _hostingEnvironment.WebRootPath + $@"\uploaded\excels";
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }
                string filePath = Path.Combine(folder, filename);

                using (FileStream fs = System.IO.File.Create(filePath))
                {
                    file.CopyTo(fs);
                    fs.Flush();
                }
                _productService.ImportExcel(filePath, categoryId);
                _productService.Save();
                return new OkObjectResult(filePath);
            }
            return new NoContentResult();
        }

        [HttpPost]
        public IActionResult ExportExcel()
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string directory = Path.Combine(sWebRootFolder, "export-files");
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
            string sFileName = $"Product_{DateTime.Now:yyyyMMddhhmmss}.xlsx";
            string fileUrl = $"{Request.Scheme}://{Request.Host}/export-files/{sFileName}";
            FileInfo file = new FileInfo(Path.Combine(directory, sFileName));
            if (file.Exists)
            {
                file.Delete();
                file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            }
            //var products = _productService.GetAll();
            //using (ExcelPackage package = new ExcelPackage(file))
            //{
            //    // add a new worksheet to the empty workbook
            //    ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Products");
            //    worksheet.Cells["A1"].LoadFromCollection(products, true, TableStyles.Light1);
            //    worksheet.Cells.AutoFitColumns();
            //    package.Save(); //Save the workbook.
            //}
            return new OkObjectResult(fileUrl);
        }
        #endregion
    }
}

BeCoreApp.Web/Controllers/Components/PagerViewComponent.cs
using BeCoreApp.Application.Interfaces;
using BeCoreApp.Utilities.Dtos;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeCoreApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

BeCoreApp.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeCoreApp.Application.Interfaces;
using BeCoreApp.Models.ProductViewModels;
using BeCoreApp.Utilities.Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace BeCoreApp.Controllers
{
    public class ProductController : Controller
    {
        IBlogCategoryService _blogCategoryService;
        IBlogService _blogService;
        IProductService _productService;
        IBillService _billService;
        IConfiguration _configuration;
        public ProductController(IProductService productService, IBlogCategoryService blogCategoryService,
        IBlogService blogService, IConfiguration configuration, IBillService billService)
        {
            _blogCategoryService = blogCategoryService;
            _blogService = blogService;
            _productService = productService;
            _configuration = configuration;
            _billService = billService;
        }

        [Route("{alias}-pc.{id}.html")]
        public IActionResult Catalog(int id, int? pageSize, int page = 1)
        {
            var catalog = new CatalogViewModel();
            catalog.BlogCategory = _blogCategoryService.GetById(id);
            if (pageSize == null)
                pageSize = _configuration.GetValue<int>("ProductPageSize");

            catalog.PageSize = pageSize;
            catalog.Data = _productService.GetAllPaging("", "", "", id, page, pageSize.Value);
            catalog.Tags = _blogService.GetListTagByType(CommonConstants.ProductTag);

            return View(catalog);
        }

        [Route("chu-de-san-pham/{id}.html")]
        public IActionResult ProductTag(string id, int? pageSize, int page = 1)
        {
            var catalog = new CatalogViewModel();
            catalog.Tag = _blogService.GetTagById(id);
            if (pageSize == null)
                pageSize = _configuration.GetValue<int>("ProductPageSize");

            catalog.PageSize = pageSize;
            catalog.Data = _productService.GetAllByTagId(id, page, pageSize.Value);
            catalog.Tags = _productService.GetListTagByType(CommonConstants.ProductTag);

            return View(catalog);
        }



        [Route("{alias}-p.{id}.html", Name = "ProductDetail")]
        public IActionResult Details(int id)
        {
            var model = new DetailViewModel();
            model.Product = _productService.GetById(id);
            model.ProductTags = _productService.GetProductTags(id);
            model.RelatedProducts = _productService.GetRelatedProducts(id, 9);
            model.Tags = _productService.GetListTagByType(CommonConstants.ProductTag);

            return View(model);
        }
    }
}

BeCoreApp.Web/Views/Product/Catalog.cshtml
@model BeCoreApp.Models.ProductViewModels.CatalogViewModel
@{
    ViewData["Title"] = Model.Data.CurrentPage == 1 ? Model.BlogCategory.Name : Model.BlogCategory.Name + " - Page " + Model.Data.CurrentPage;
    ViewData["MetaKeyword"] = Model.Data.CurrentPage == 1 ? Model.BlogCategory.SeoKeywords : Model.BlogCategory.SeoKeywords + " - Page " + Model.Data.CurrentPage;
    ViewData["MetaDescription"] = Model.Data.CurrentPage == 1 ? Model.BlogCategory.SeoDescription : Model.BlogCategory.SeoDescription + " - Page " + Model.Data.CurrentPage;
}
<div id="tbay-main-content">
    <section id="tbay-breadscrumb" class="tbay-breadscrumb">
        <div class="container">
            <div class="breadscrumb-inner">
                <ol class="tbay-woocommerce-breadcrumb breadcrumb">
                    <li><a href="/">Trang Chủ</a></li>
                    <li><a href="/">Sản Phẩm</a></li>
                    <li>@Model.BlogCategory.Name</li>
                </ol>
            </div>
        </div>
    </section>

    <section id="main-container" class="main-content container">
        <div class="row">
            <div id="main-content" class="archive-shop col-xs-12 col-xs-12 col-md-12 col-lg-9 pull-right">
                <div id="primary" class="content-area">
                    <div id="content" class="site-content" role="main">
                        <div class="tbay-filter">
                            <div class="display-mode-warpper display-mode">
                                <a href="javascript:void(0);" id="display-mode-grid" class="change-view display-mode-btn active" title="'Grid'"><i class="ti-layout-grid2"></i></a>
                                <a href="javascript:void(0);" id="display-mode-list" class="change-view display-mode-btn list " title="'List'"><i class="ti-view-list"></i></a>
                            </div>
                            <div class="woocommerce-notices-wrapper"></div>
                            <p class="woocommerce-result-count">
                                @Model.BlogCategory.Name - @Model.Data.RowCount sản phẩm
                            </p>
                            <form class="woocommerce-ordering" method="get">
                                <span>Sort by: </span>
                                <select name="orderby" class="orderby" aria-label="Shop order">
                                    <option value="menu_order" selected='selected'>Default sorting</option>
                                    <option value="popularity">Sort by popularity</option>
                                </select>
                            </form>
                        </div>

                        <div class="products products-grid">
                            <div class="row" data-xlgdesktop=3 data-desktop=3 data-desktopsmall=3 data-tablet=2 data-mobile=2>

                                @foreach (var product in Model.Data.Results)
                                {
                                    var productDetailUrl = $"/{product.SeoAlias}-p.{product.Id}.html";
                                    //status-publish instock product_cat-milk-cream product_cat-ocean-foods product_cat-vegetables product_tag-fruit-theme product_tag-organic-food product_tag-organic-shop has-post-thumbnail featured taxable shipping-taxable purchasable product-type-variable has-default-attributes
                                    <div class="product-box col-xs-6 col-lg-4 col-md-4 col-sm-6 grid product ">
                                        <div class="product-block grid ">
                                            <div class="product-content">
                                                <div class="block-inner">
                                                    <figure class="image">
                                                        <a title="@product.Name" href="@productDetailUrl" class="product-image">
                                                            @if (product.ProductImages.Count < 0)
                                                            {
                                                                <img width="405" height="330" src="@product.ProductImages[0].Path" class="attachment-shop_catalog image-effect wp-post-image" alt="@product.Name" />
                                                                <img width="405" height="330" src="@product.ProductImages[1].Path" class="image-hover wp-post-image" alt="@product.Name" />
                                                            }
                                                            else
                                                            {
                                                                <img width="405" height="330" src="@product.Image" class="attachment-shop_catalog image-effect wp-post-image" alt="@product.Name" />
                                                                <img width="405" height="330" src="@product.Image" class="image-hover wp-post-image" alt="@product.Name" />
                                                            }

                                                            @if (product.PromotionPrice.HasValue && product.PromotionPrice.Value > 0)
                                                            {
                                                                <span class="onsale">
                                                                    <span class="featured not-sale">- @Convert.ToInt32((product.Price - product.PromotionPrice) / product.Price * 100)%</span>
                                                                </span>
                                                            }
                                                        </a>
                                                        <ul class="show-brand">
                                                            @foreach (var productTag in product.ProductTags)
                                                            {
                                                                var tagDetailUrl = $"/chu-de-san-pham/{productTag.TagId}.html";
                                                                <li><a href="@tagDetailUrl">@productTag.Tag.Name</a></li>
                                                            }
                                                        </ul>
                                                    </figure>
                                                </div>
                                                <div class="caption">
                                                    <div class="meta">
                                                        <div class="infor">
                                                            <div class="name-subtitle">
                                                                <h3 class="name"><a href="@productDetailUrl">@product.Name</a></h3>
                                                                <div class="tbay-subtitle">(@product.ProductType.Name)</div>
                                                            </div>
                                                            <span class="price">
                                                                @if (product.PromotionPrice.HasValue && product.PromotionPrice.Value > 0)
                                                                {
                                                                    <del>
                                                                        <span class="woocommerce-Price-amount amount">@String.Format("{0:n0}", product.Price)đ</span>
                                                                    </del>
                                                                    <ins>
                                                                        <span class="woocommerce-Price-amount amount">@String.Format("{0:n0}", product.PromotionPrice)đ</span>
                                                                    </ins>
                                                                }
                                                                else
                                                                {
                                                                    <ins>
                                                                        <span class="woocommerce-Price-amount amount">@String.Format("{0:n0}", product.Price)đ</span>
                                                                    </ins>
                                                                }
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="groups-button clearfix">
                                                        <div class="add-cart" title="Add to cart">
                                                            <a href="@productDetailUrl" rel="nofollow" class="button product_type_simple product_type_simple">
                                                                <i class="icofont-shopping-cart"></i> <span class="title-cart">Chọn sản phẩm</span>
                                                            </a>
                                                        </div>
                                                        <a href="@productDetailUrl" class="button yith-wcqv-button tbay-tooltip btn-view-fast-product" data-id="@product.Id" title="Xem nhanh">
                                                            <span><i class="icofont-eye-alt"></i></span>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>

                        @await Component.InvokeAsync("Pager", Model.Data)
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-12 col-lg-3">
                <aside class="sidebar sidebar-left">
                    <aside id="tbay_custom_menu-2" class="widget widget_tbay_custom_menu hidden-xs">
                        @await Component.InvokeAsync("HomeSidebarMenu")
                    </aside>

                    <aside id="woocommerce_product_tag_cloud-3" class="widget woocommerce widget_product_tag_cloud">
                        <h2 class="widget-title">Chủ Đề ( Tags )</h2><div class="tagcloud">
                            @foreach (var tag in Model.Tags)
                            {
                                var tagDetailUrl = $"/chu-de-san-pham/{tag.Id}.html";
                                <a href="@tagDetailUrl" class="tag-cloud-link" style="font-size: 8pt;">@tag.Name</a>
                            }
                        </div>
                    </aside>
                </aside>
            </div>
        </div>
    </section>
</div>

BeCoreApp.Web/Views/Product/Index.cshtml
@*@model List<MainMenuViewModel>
@{
    ViewData["Title"] = "All product  categories";
}
<!-- Breadcrumbs -->

<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li class="home"> <a title="Go to Home Page" href="/">Home</a><span>&raquo;</span></li>
                    <li><strong>Product categories</strong></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumbs End -->
<!-- Main Container -->
<div class="main-container col1-layout">
    <div class="container">
        <div class="row">
            <div class="col-main col-sm-12 col-xs-12">
                <div class="shop-inner">
                    <div class="page-title">
                        <h2>Product categories</h2>
                    </div>

                    <div class="product-grid-area">
                        <ul class="products-grid">
                            @foreach (var item in Model)
                            {
                                var url = "/" + item.SeoAlias + "-c." + item.Id + ".html";
                                <li class="item col-lg-3 col-md-4 col-sm-6 col-xs-6 ">
                                    <div class="product-item">
                                        <div class="item-inner">
                                            <div class="product-thumbnail">
                                                <div class="icon-sale-label sale-left">Sale</div>
                                                <div class="icon-new-label new-right">New</div>
                                                <div class="pr-img-area">
                                                    <a title="@item.Name" href="@url">
                                                        <figure> <img class="first-img" src="@item.Image" alt="@item.Name"> <img class="hover-img" src="@item.Image" alt="@item.Name"></figure>
                                                    </a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </li>

                            }

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Container End -->*@